name: CMake Build with SDL2 and SDL2_ttf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v1
      with:
        msys2-version: '202308'
        update: true
        packages: 'mingw-w64-x86_64-toolchain'

    - name: Install SDL2 and SDL2_ttf
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_ttf

    - name: Setup CMake
      uses: scikit-build/scikit-build-action@v1
      with:
        cmake-version: '3.26.2'

    - name: Configure CMake
      run: cmake -Bbuild -G "MinGW Makefiles"

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build
