name: CMake Build with SDL2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Install SDL2 and SDL2_ttf
      run: |
        choco install sdl2 sdl2_ttf
        echo "SDL2_DIR=C:/tools/SDL2-2.26.5/cmake" >> $GITHUB_ENV
        echo "SDL2_TTF_DIR=C:/tools/SDL2_ttf-2.20.2/cmake" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
