name: Build with MinGW Makefiles

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install mingw -y
        choco install cmake -y

    - name: Set reusable strings
      id: strings
      run: echo "build-output-dir=${{ github.workspace }}\build" >> $env:GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake -B $env:GITHUB_WORKSPACE/build -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -S $env:GITHUB_WORKSPACE

    - name: Build
      run: cmake --build $env:GITHUB_WORKSPACE/build

    - name: Test
      working-directory: ${{ env.GITHUB_WORKSPACE }}/build
      run: ctest
